{
 "title": "LoadBalancer",
 "tags": [ "CloudMon" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "graphite" },
   { "name": "environment", "label": "Environment", "query": "stats.timers.cloudmon.*" },
   { "name": "zone", "label": "Zone", "query": "stats.timers.cloudmon.*.*" },
   {
    "name": "loadbalancer",
    "label": "Loadbalancer",
    "query": "stats.timers.cloudmon.*.*.loadbalancer.*"
   }
  ]
 },
 "panels": [
  {
   "title": "LoadBalancer Latency per AZ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "groupByNodes(stats.timers.cloudmon.$environment.$zone.loadbalancer.$loadbalancer.*.*.mean, 'avg', 3, 4, 6, 8)"
    }
   ]
  },
  {
   "title": "LoadBalancer Latency per type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "groupByNodes(stats.timers.cloudmon.$environment.$zone.loadbalancer.$loadbalancer.*.*.mean, 'avg', 3, 4, 6, 7)"
    }
   ]
  },
  {
   "title": "LoadBalancer Latency per type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "target": "aliasByNode(removeBelowValue(isNonNull(groupByNodes(stats.counters.cloudmon.$environment.$zone.loadbalancer.$loadbalancer.*.failed.count, 'sum', 3, 4, 6, 7)), 1), 'name')"
    }
   ]
  },
  {
   "title": "Request distribution per AZ",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByMetric(aggregateLine(groupByNode(stats.timers.cloudmon.$environment.$zone.loadbalancer.$loadbalancer.*.*.count, 8, 'sum'), 'sum', false))"
    }
   ]
  },
  {
   "title": "Request duration per listener type",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByMetric(consolidateBy(groupByNode(stats.timers.cloudmon.$environment.$zone.loadbalancer.$loadbalancer.*.*.mean, 7, 'avg'), 'avg'))"
    }
   ]
  },
  {
   "title": "Failures",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByNode(smartSummarize(applyByNode(stats.counters.cloudmon.$environment.$zone.loadbalancer.$loadbalancer.*.*.count, 7, 'asPercent(sumSeries(%.failed.count), sumSeries(%.attempted.count))', '%'), '1m', 'avg'), 3, 4, 6, 7)"
    }
   ]
  }
 ]
}